### ISSUE TITLE
Small bug at line 9.

### ISSUE THREAD

**Issue by rich123** [BY-jk/pwned#1]
https://github.com/BY-jk/pwned/blob/3739a502bc4a4f6225282c1f04306a38c3232ced/pwned#L9

Note that for passwords containing spaces, qw() does not produce correct output:

$ PASSWORD="testing qw"
$ perl -e "print qw($PASSWORD)" ; echo
testingqw

We want "testing qw" to be piped into shasum.  But we get "testingqw" (without the embedded space) instead.  Which is a different password.

Just use printf instead (note the quotes around the expansion of $PASSWORD are important):

PWDSHASUM=`printf %s "$PASSWORD" | shasum`

Also, if you are writing this specifically for bash (that's what your shebang line says, then consider using $() instead of back ticks.

**Comment by jank** [comment]
@rich123 thanks for your close look and for reporting this. Will be fixed.
